version: "3.8"

services:
  postgres-database:
    image: postgres:15.4-alpine3.18
    container_name: postgres-database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # mongo-database:
  #   image: mongo:latest
  #   container_name: mongo-database
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongo-data:/data/db
  #   healthcheck:
  #     test: echo 'db.runCommand("ping").ok' | mongo mongo-database:27017/test --quiet
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  redis-cache:
    image: redis:alpine3.18
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
      - ./redis-data/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  mongo-data:
  redis-data:

networks:
  default:
    name: ${NETWORK_NAME}
