CREATE TABLE IF NOT EXISTS platform_switches (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    from_platform VARCHAR(255) NOT NULL,
    to_platform VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    login_id BIGINT NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
)