   CREATE TABLE IF NOT EXISTS account_positions (
          id SERIAL PRIMARY KEY,
          region_id VARCHAR(16),
          system_id VARCHAR(16),
          system_date DATE,
          account VARCHAR(32),
          sub_acct_no VARCHAR(32),
          acct_grp VARCHAR(16),
          currency VARCHAR(16),
          symbol VARCHAR(32),
          symbol_num VARCHAR(32),
          security_type VARCHAR(16),
          price DECIMAL(16, 2),
          price_date DATE,
          trade_date_value DECIMAL(16, 2),
          trade_date_qty DECIMAL(16, 2),
          settle_date_value DECIMAL(16, 2),
          settle_date_qty DECIMAL(16, 2),
          avg_price DECIMAL(16, 2),
          total_cost DECIMAL(16, 2),
          fed_margin DECIMAL(16, 2),
          exch_margin DECIMAL(16, 2),
          house_margin DECIMAL(16, 2),
          sec_desc VARCHAR(128),
          expiration VARCHAR(32),
          margin_eligible VARCHAR(16),
          strike_price DECIMAL(16, 2),
          underlying_cusip VARCHAR(32),
          underlying_price DECIMAL(16, 2),
          underlying_symbol VARCHAR(32),
          file_date DATE,
          insert_time DATE
          );