insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AF', 'Afghanistan');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AL', 'Albania');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'DZ', 'Algeria');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AD', 'Andorra');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AO', 'Angola');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AI', 'Anguilla');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AQ', 'Antarctica');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AG', 'Antigua and Barbuda');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AR', 'Argentina');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AM', 'Armenia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AW', 'Aruba');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AU', 'Australia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AT', 'Austria');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AZ', 'Azerbaijan');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BS', 'Bahamas');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BH', 'Bahrain');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BD', 'Bangladesh');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BB', 'Barbados');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BY', 'Belarus');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BE', 'Belgium');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BZ', 'Belize');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BJ', 'Benin');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BM', 'Bermuda');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BT', 'Bhutan');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BO', 'Bolivia (Plurinational State of)');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BQ', 'Bonaire, Sint Eustatius and Saba');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BA', 'Bosnia and Herzegovina');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BW', 'Botswana');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BV', 'Bouvet Island');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BR', 'Brazil');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'IO', 'British Indian Ocean Territory');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BN', 'Brunei Darussalam');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BF', 'Burkina Faso');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BI', 'Burundi');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CV', 'Cabo Verde');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'KH', 'Cambodia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CM', 'Cameroon');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CA', 'Canada');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'KY', 'Cayman Islands');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CF', 'Central African Republic');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TD', 'Chad');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CL', 'Chile');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CN', 'China');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CX', 'Christmas Island');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CC', 'Cocos (Keeling) Islands');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CO', 'Colombia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'KM', 'Comoros');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CD', 'Congo (the Democratic Republic of the)');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CG', 'Congo');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CK', 'Cook Islands');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CR', 'Costa Rica');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'HR', 'Croatia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CU', 'Cuba');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CW', 'Curaçao');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CY', 'Cyprus');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CZ', 'Czechia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CI', 'Côte d''Ivoire');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'DK', 'Denmark');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'DJ', 'Djibouti');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'DM', 'Dominica');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'DO', 'Dominican Republic');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'EC', 'Ecuador');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'EG', 'Egypt');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SV', 'El Salvador');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GQ', 'Equatorial Guinea');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'ER', 'Eritrea');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'EE', 'Estonia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SZ', 'Eswatini');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'ET', 'Ethiopia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'FK', 'Falkland Islands [Malvinas]');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'FO', 'Faroe Islands');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'FJ', 'Fiji');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'FI', 'Finland');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'FR', 'France');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GF', 'French Guiana');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PF', 'French Polynesia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TF', 'French Southern Territories');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GA', 'Gabon');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GM', 'Gambia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GE', 'Georgia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'DE', 'Germany');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GH', 'Ghana');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GI', 'Gibraltar');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GR', 'Greece');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GL', 'Greenland');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GD', 'Grenada');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GP', 'Guadeloupe');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GT', 'Guatemala');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GG', 'Guernsey');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GN', 'Guinea');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GW', 'Guinea-Bissau');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GY', 'Guyana');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'HT', 'Haiti');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'HM', 'Heard Island and McDonald Islands');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'VA', 'Holy See');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'HN', 'Honduras');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'HK', 'Hong Kong');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'HU', 'Hungary');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'IS', 'Iceland');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'IN', 'India');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'IR', 'Iran (Islamic Republic of)');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'IQ', 'Iraq');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'IE', 'Ireland');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'IM', 'Isle of Man');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'IL', 'Israel');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'IT', 'Italy');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'JM', 'Jamaica');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'JP', 'Japan');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'JE', 'Jersey');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'JO', 'Jordan');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'KZ', 'Kazakhstan');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BG', 'Bulgaria');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'ID', 'Indonesia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'KE', 'Kenya');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'KI', 'Kiribati');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'KP', 'Korea (the Democratic People''s Republic of)');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'KR', 'Korea (the Republic of)');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'KW', 'Kuwait');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'KG', 'Kyrgyzstan');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'LA', 'Lao People''s Democratic Republic');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'LB', 'Lebanon');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'LS', 'Lesotho');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'LR', 'Liberia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'LY', 'Libya');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'LI', 'Liechtenstein');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'LT', 'Lithuania');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'LU', 'Luxembourg');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MO', 'Macao');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MG', 'Madagascar');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MW', 'Malawi');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MV', 'Maldives');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'ML', 'Mali');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MT', 'Malta');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MH', 'Marshall Islands');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MQ', 'Martinique');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MR', 'Mauritania');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MU', 'Mauritius');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'YT', 'Mayotte');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MX', 'Mexico');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'FM', 'Micronesia (Federated States of)');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MD', 'Moldova (the Republic of)');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MC', 'Monaco');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MN', 'Mongolia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'ME', 'Montenegro');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MS', 'Montserrat');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MA', 'Morocco');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MZ', 'Mozambique');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MM', 'Myanmar');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'NA', 'Namibia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'NR', 'Nauru');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'NP', 'Nepal');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'NL', 'Netherlands');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'NC', 'New Caledonia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'NZ', 'New Zealand');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'NI', 'Nicaragua');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'NE', 'Niger');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'NG', 'Nigeria');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'NU', 'Niue');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'NF', 'Norfolk Island');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MP', 'Northern Mariana Islands');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'NO', 'Norway');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'OM', 'Oman');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PK', 'Pakistan');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PW', 'Palau');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PS', 'Palestine, State of');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PA', 'Panama');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PG', 'Papua New Guinea');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PY', 'Paraguay');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PE', 'Peru');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PH', 'Philippines');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PN', 'Pitcairn');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PL', 'Poland');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PT', 'Portugal');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'QA', 'Qatar');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MK', 'Republic of North Macedonia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'RU', 'Russian Federation');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'RW', 'Rwanda');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'RE', 'Réunion');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'BL', 'Saint Barthélemy');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SH', 'Saint Helena, Ascension and Tristan da Cunha');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'KN', 'Saint Kitts and Nevis');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'LC', 'Saint Lucia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MF', 'Saint Martin (French part)');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PM', 'Saint Pierre and Miquelon');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'VC', 'Saint Vincent and the Grenadines');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'WS', 'Samoa');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SM', 'San Marino');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'ST', 'Sao Tome and Principe');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SA', 'Saudi Arabia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SN', 'Senegal');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'RS', 'Serbia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SC', 'Seychelles');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SL', 'Sierra Leone');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SG', 'Singapore');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SX', 'Sint Maarten (Dutch part)');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SK', 'Slovakia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SB', 'Solomon Islands');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SO', 'Somalia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'ZA', 'South Africa');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GS', 'South Georgia and the South Sandwich Islands');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SS', 'South Sudan');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'ES', 'Spain');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'LK', 'Sri Lanka');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SD', 'Sudan');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SR', 'Suriname');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SJ', 'Svalbard and Jan Mayen');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SE', 'Sweden');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'CH', 'Switzerland');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SY', 'Syrian Arab Republic');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TJ', 'Tajikistan');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TZ', 'Tanzania, United Republic of');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TL', 'Timor-Leste');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TG', 'Togo');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TK', 'Tokelau');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TO', 'Tonga');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TT', 'Trinidad and Tobago');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TN', 'Tunisia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TR', 'Turkey');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'RO', 'Romania');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'SI', 'Slovenia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'MY', 'Malaysia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TH', 'Thailand');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'LV', 'Latvia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TW', 'Taiwan (Province of China)');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TM', 'Turkmenistan');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TC', 'Turks and Caicos Islands');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'TV', 'Tuvalu');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'UG', 'Uganda');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'UA', 'Ukraine');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AE', 'United Arab Emirates');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GB', 'United Kingdom of Great Britain and Northern Ireland');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'US', 'United States of America');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'UY', 'Uruguay');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'UZ', 'Uzbekistan');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'VU', 'Vanuatu');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'VE', 'Venezuela (Bolivarian Republic of)');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'VG', 'Virgin Islands (British)');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'WF', 'Wallis and Futuna');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'EH', 'Western Sahara');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'YE', 'Yemen');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'ZM', 'Zambia');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'ZW', 'Zimbabwe');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'GU', 'Guam');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'PR', 'Puerto Rico');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'AS', 'American Samoa');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'VI', 'Virgin Islands (U.S.)');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'UM', 'United States Minor Outlying Islands');
insert into country_codes (created_at, updated_at, blacklisted, code, name) values(now(), now(), TRUE, 'VN', 'Viet Nam');


update country_codes set blacklisted = true;

update country_codes set blacklisted = FALSE 
where code in ('AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','DE',
'GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','SK','SI','ES','SE','GB');