delete from public.pdf_form_questions;
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'required','USPCERT',NULL,NULL,8,'I certify that I have the capacity to sign','certificationCheckbox1',2,'I certify that I have the capacity to sign','CheckBox',8),
	 (NULL,NULL,'required','USPCERT',162,15,50,'Type Signature ID here','headerSignature1',3,'Type Signature ID here','StringSignature',315),
	 (NULL,NULL,'required','USPCERT',76,304,50,'Type Signature ID here','certificationSignature',2,'Type Signature ID here','StringSignature',315),
	 (NULL,NULL,'required','USPCERT',209,704,NULL,'Initial Part A and sign at the end of the form confirming that you are not a U.S. Person','question1a',2,'Type Initials','String',NULL),
	 (NULL,NULL,'required','USPCERT',212,627,NULL,'Initial Part B and sign at the end of the form confirming that you are a U.S. Person.','question2a',2,'Type Initials','String',NULL),
	 (NULL,NULL,'required','USPCERT',106,365,NULL,'Date (MM-DD-YYYY)','certificationSignaturedate',2,'Date (MM-DD-YYYY)','StringSignatureDate',NULL),
	 (NULL,NULL,'required','USPCERT',162,15,50,'Type Signature ID here','headerSignature',1,'Type Signature ID here','StringSignature',315),
	 (NULL,NULL,'required','USPCERT_ES',162,15,50,'Escriba el ID de firma aquí','headerSignature',2,'Escriba el ID de firma aquí','StringSignature',315),
	 (NULL,NULL,'required','USPCERT_ES',NULL,NULL,8,'Yo certifico que tengo la capacidad de firmar','certificationCheckbox1',2,'Yo certifico que tengo la capacidad de firmar','CheckBox',8),
	 (NULL,NULL,'required','USPCERT_ES',222,214,NULL,'[Escriba sus iniciales aquí si procede]','question1a',1,'Escriba sus iniciales','String',NULL);
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'required','USPCERT_ES',212,50,50,'Escriba el ID de firma aquí','certificationSignature',1,'Escriba el ID de firma aquí','StringSignature',315),
	 (NULL,NULL,'required','USPCERT_ES',222,168,NULL,'[Escriba sus iniciales aquí si procede]','question2a',1,'Escriba sus iniciales','String',NULL),
	 (NULL,NULL,'required','USPCERT_ES',157,67,NULL,'Fecha (MM-DD-YYYY)','certificationSignaturedate',1,'Fecha (MM-DD-YYYY)','StringSignatureDate',NULL),
	 (NULL,NULL,'','W8BEN',63,314,NULL,'Special rates and conditions','question10a',1,'','String',NULL),
	 (NULL,NULL,'','W8BEN',352,314,NULL,'Special rates percentage rate','question10b',1,'percentage rate','String',NULL),
	 (NULL,NULL,'','W8BEN',63,300,NULL,'Special ratesType of Income','question10c',1,' ','String',NULL),
	 (NULL,NULL,'','W8BEN',64,279,NULL,'Explain the additional conditions in the Article and paragraph the beneficial owner meets to be eligible for the rate of withholding:','question10d',1,'Additional conditions','String',NULL),
	 (NULL,NULL,'required','W8BEN',63,541,NULL,'Name of individual who is the beneficial owner','question1a',1,'Name of individual who is the beneficial owner','String',NULL),
	 (NULL,NULL,'required','W8BEN',109,99,8,'I certify that I have the capacity to sign','certificationCheckbox1',1,'I certify that I have the capacity to sign','CheckBox',8),
	 (NULL,NULL,'','W8BEN',63,423,NULL,'U.S. taxpayer identification number (SSN or ITIN)','question5a',1,'U.S. taxpayer identification number (SSN or ITIN)','String',NULL);
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'required','W8BEN',393,541,NULL,'Country of citizenship','question2a',1,'Country of citizenship','String',NULL),
	 (NULL,NULL,'','W8BEN',63,446,NULL,'City or town, state or province.','question4b',1,'City or town, state or province.','String',NULL),
	 (NULL,NULL,'','W8BEN',442,446,NULL,'Country','question4c',1,'Country','String',NULL),
	 (NULL,NULL,'','W8BEN',63,470,NULL,'Mailing address (If different from above)','question4a',1,'Mailing address (If different from above)','String',NULL),
	 (NULL,NULL,'required','W8BEN',107,82,50,'Type Signature ID here','certificationSignature',1,'Type Signature ID here','StringSignature',315),
	 (NULL,NULL,'required','W8BEN',430,82,NULL,'Date (MM-DD-YYYY)','certificationSignaturedate',1,'Date (MM-DD-YYYY)','StringSignatureDate',NULL),
	 (NULL,NULL,'required','W8BEN',442,494,NULL,'Country','question3c',1,'Country','String',NULL),
	 (NULL,NULL,'required','W8BEN',107,50,NULL,'Type Name of Signer here','certificationSignatureName',1,'Type Name of Signer','String',NULL),
	 (NULL,NULL,'required','W8BEN',63,494,NULL,'City or town, state or province.','question3b',1,'City or town, state or province.','String',NULL),
	 (NULL,NULL,'required','W8BEN',63,519,NULL,'Permanent residence address','question3a',1,'Permanent residence address','String',NULL);
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'required','W8BEN',239,352,NULL,'Resident of Certification','question9a',1,'Country of Residence','String',NULL),
	 (NULL,NULL,'','W8BEN',312,375,NULL,'Date of birth (MM-DD-YYYY)','question8a',1,'Date of birth (MM-DD-YYYY)','String',NULL),
	 (NULL,NULL,'','W8BEN',63,376,NULL,'Reference number','question7a',1,'Reference number','String',NULL),
	 (NULL,NULL,'','W8BEN',563,410,8,'Check if FTIN not legally required','question6b',1,'Check if FTIN not legally required','CheckBox',8),
	 (NULL,NULL,'','W8BEN',63,397,NULL,'Foreign tax identifying number','question6a',1,'Foreign tax identifying number','String',NULL),
	 (NULL,NULL,'','W9',461,386,8,'EID2','question9b',1,'EID2','StringID',NULL),
	 (NULL,NULL,'required','W9',NULL,NULL,8,'I certify that I have the capacity to sign','certificationCheckbox1',1,'I certify that I have the capacity to sign','CheckBox',8),
	 (NULL,NULL,'required','W9',125,231,50,'Type Signature ID here','certificationSignature',1,'Type Signature ID here','StringSignature',315),
	 (NULL,NULL,'required','W9',68,684,NULL,'Name (as shown on your income tax return)','question1a',1,'Enter name','String',NULL),
	 (NULL,NULL,' ','W9',68,660,NULL,'Business name/disregarded entity name, if different from above','question2a',1,'Enter business name','String',NULL);
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'','W9',413,230,NULL,'Date (MM-DD-YYYY)','certificationSignaturedate',1,'Date (MM-DD-YYYY)','StringSignatureDate',NULL),
	 (NULL,NULL,'','W9',162,15,50,'Type Signature ID here','headerSignature',2,'Type Signature ID here','StringSignature',315),
	 (NULL,NULL,'','W9',162,15,50,'Type Signature ID here','headerSignature1',3,'Type Signature ID here','StringSignature',315),
	 (NULL,NULL,'','W9',162,15,50,'Type Signature ID here','headerSignature2',4,'Type Signature ID here','StringSignature',315),
	 (NULL,NULL,'','W9',162,15,50,'Type Signature ID here','headerSignature3',5,'Type Signature ID here','StringSignature',315),
	 (NULL,NULL,'','W9',162,15,50,'Type Signature ID here','headerSignature4',6,'Type Signature ID here','StringSignature',315),
	 (NULL,NULL,'','W9',71,631,8,'Not to be Shown','question3',1,'Main Question 3','RadioMain',8),
	 (NULL,NULL,'','W9',65,624,8,'Individual/Sole proprietor','question3a',1,'Individual/Sole proprietor','RadioOption',8),
	 (NULL,NULL,'','W9',180,626,8,'C Corporation','question3b',1,'C Corporation','RadioOption',8),
	 (NULL,NULL,'','W9',252,626,8,'S Corporation','question3c',1,'S Corporation','RadioOption',8);
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'','W9',324,326,8,'Partnership','question3d',1,'Partnership','RadioOption',8),
	 (NULL,NULL,'','W9',396,626,8,'Trust/estate','question3e',1,'Trust/estate','RadioOption',8),
	 (NULL,NULL,'','W9',65,599,8,'Limited liability company','question3f',1,'Limited liability company','RadioOption',8),
	 (NULL,NULL,'','W9',412,600,NULL,'(C= C Corporation, S=S Corporation, P=Partnership)','question3g',1,'Enter the tax classification','String',NULL),
	 (NULL,NULL,'','W9',65,553,8,'Other','question3h',1,'Other','RadioOption',8),
	 (NULL,NULL,'','W9',162,555,NULL,'(see instructions)','question3i',1,'Other details','String',NULL),
	 (NULL,NULL,'','W9',543,614,NULL,'Exempt payee code (if any)','question4a',1,'code (if any)','String',NULL),
	 (NULL,NULL,'','W9',506,575,NULL,'Exemption from FATCA reporting code (if any)','question4b',1,'code (if any)','String',NULL),
	 (NULL,NULL,'required','W9',68,529,NULL,'Address (number, street, and apt or suite no.)','question5a',1,'Address (number, street, and apt or suite no.)','String',NULL),
	 (NULL,NULL,'required','W9',69,505,NULL,'City, state and ZIP code','question5b',1,'City, state and ZIP code','String',NULL);
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'','W9',393,531,NULL,'Requester''s name (optional)','question6a',1,'Requester''s name (optional)','String',NULL),
	 (NULL,NULL,'','W9',393,506,NULL,'Requester''s address (optional)','question6b',1,'Requester''s address (optional)','String',NULL),
	 (NULL,NULL,'','W9',69,481,NULL,'List account number(s) here (optional)','question7a',1,'List account number(s) here (optional)','String',NULL),
	 (NULL,NULL,'required','W9',417,432,NULL,'SSN1','question8a',1,'SSN1','StringID',NULL),
	 (NULL,NULL,'required','W9',476,432,NULL,'SSN2','question8b',1,'SSN2','StringID',NULL),
	 (NULL,NULL,'required','W9',519,432,NULL,'SSN3','question8c',1,'SSN3','StringID',NULL),
	 (NULL,NULL,'','W9',417,386,NULL,'EID1','question9a',1,'EID1','StringID',NULL),
	 (NULL,NULL,'required','W9_ES',519,411,NULL,'SSN3','question8c',1,'SSN3','StringID',NULL),
	 (NULL,NULL,'required','W9_ES',68,684,NULL,'Nombre (como aparece en su declaración de impuesto a la renta)','question1a',1,'Escriba nombre','String',NULL),
	 (NULL,NULL,'required','W9_ES',NULL,NULL,8,'Yo certifico que tengo la capacidad de firmar','certificationCheckbox1',1,'Yo certifico que tengo la capacidad de firmar','CheckBox',8);
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'','W9_ES',421,160,NULL,'Fecha (MM-DD-YYYY)','certificationSignaturedate',1,'Fecha (MM-DD-YYYY)','StringSignatureDate',NULL),
	 (NULL,NULL,'','W9_ES',450,591,NULL,'Exención de código de informe FATCA (si lo hubiera)','question4b',1,'código (si lo hubiera)','String',NULL),
	 (NULL,NULL,'','W9_ES',71,631,8,'Not to be Shown','question3',1,'Main Question 3','RadioMain',8),
	 (NULL,NULL,'','W9_ES',162,15,50,'Escriba el ID de firma aquí','headerSignature',2,'Escriba el ID de firma aquí','StringSignature',315),
	 (NULL,NULL,'','W9_ES',68,519,NULL,'Dirección (número, calle, y número de departamento o suite)','question5a',1,'Dirección (número, calle, y número de departamento o suite)','String',NULL),
	 (NULL,NULL,'','W9_ES',68,660,NULL,'Nombre comercial/nombre de entidad excluida, si es diferente a lo anterior','question2a',1,'Escriba nombre comercial','String',NULL),
	 (NULL,NULL,'','W9_ES',68,494,NULL,'Ciudad, estado y código postal','question5b',1,'Ciudad, estado y código postal','String',NULL),
	 (NULL,NULL,'','W9_ES',417,361,NULL,'EID1','question9a',1,'EID1','StringID',NULL),
	 (NULL,NULL,'','W9_ES',461,361,8,'EID2','question9b',1,'EID2','StringID',NULL),
	 (NULL,NULL,'','W9_ES',162,9,50,'Escriba el ID de firma aquí','headerSignature4',6,'Escriba el ID de firma aquí','StringSignature',315);
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'','W9_ES',64,627,8,'Individual/Propietario único','question3a',1,'Individual/Propietario único','RadioOption',8),
	 (NULL,NULL,'','W9_ES',290,626,8,'Sociedad anónima tipo C','question3b',1,'Corporación C','RadioOption',8),
	 (NULL,NULL,'','W9_ES',393,524,NULL,'Nombre del solicitante (opcional)','question6a',1,'Nombre del solicitante (opcional)','String',NULL),
	 (NULL,NULL,'required','W9_ES',417,411,NULL,'SSN1','question8a',1,'SSN1','StringID',NULL),
	 (NULL,NULL,'','W9_ES',64,614,8,'Sociedad anónima tipo S','question3c',1,'S Corporation','RadioOption',8),
	 (NULL,NULL,'required','W9_ES',161,160,50,'Escriba el ID de firma aquí','certificationSignature',1,'Escriba el ID de firma aquí','StringSignature',315),
	 (NULL,NULL,'','W9_ES',165,614,8,'Sociedad colectiva','question3d',1,'Sociedad','RadioOption',8),
	 (NULL,NULL,'','W9_ES',162,15,50,'Escriba el ID de firma aquí','headerSignature3',5,'Escriba el ID de firma aquí','StringSignature',315),
	 (NULL,NULL,'','W9_ES',244,614,8,'Fideicomiso/caudal hereditario','question3e',1,'Fideicomiso/patrimonio','RadioOption',8),
	 (NULL,NULL,'','W9_ES',393,506,NULL,'Dirección del solicitante (opcional)','question6b',1,'Dirección del solicitante (opcional)','String',NULL);
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'required','W9_ES',476,411,NULL,'SSN2','question8b',1,'SSN2','StringID',NULL),
	 (NULL,NULL,'','W9_ES',64,603,8,'Sociedad anónima','question3f',1,'Sociedad anónima','RadioOption',8),
	 (NULL,NULL,'','W9_ES',162,15,50,'Escriba el ID de firma aquí','headerSignature2',4,'Escriba el ID de firma aquí','StringSignature',315),
	 (NULL,NULL,'','W9_ES',221,588,NULL,'Cía. de responsabilidad limitada (LLC). Anote la clasificación tributaria (C=Soc. anónima tipo C, S=Soc. anónima tipo S, P=Soc. colectiva)','question3g',1,'Ingrese la clasificación fiscal','String',NULL),
	 (NULL,NULL,'','W9_ES',64,542,8,'Otro','question3h',1,'Otro','RadioOption',8),
	 (NULL,NULL,'','W9_ES',68,470,NULL,'Enumere el(los) número(s) de cuenta(s) aquí (opcional)','question7a',1,'Enumere el(los) número(s) de cuenta(s) aquí (opcional)','String',NULL),
	 (NULL,NULL,'','W9_ES',162,15,50,'Escriba el ID de firma aquí','headerSignature1',3,'Escriba el ID de firma aquí','StringSignature',315),
	 (NULL,NULL,'','W9_ES',172,541,NULL,'(consultar instrucciones)','question3i',1,'(consultar instrucciones)','String',NULL),
	 (NULL,NULL,'','W9_ES',521,626,NULL,'Código de beneficiario exento (si lo hubiera)','question4a',1,'código (si lo hubiera)','String',NULL);
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'required','W9_PT',NULL,NULL,8,'Certifico que tenho capacidade para assinar','certificationCheckbox1',1,'Certifico que tenho capacidade para assinar','CheckBox',8),
	 (NULL,NULL,'required','W9_PT',125,231,50,'Digite o ID da assinatura aqui','certificationSignature',1,'Digite o ID da assinatura aqui','StringSignature',315),
	 (NULL,NULL,'required','W9_PT',413,230,NULL,'Data (MM-DD-YYYY)','certificationSignaturedate',1,'Data (MM-DD-YYYY)','StringSignatureDate',NULL),
	 (NULL,NULL,'required','W9_PT',162,15,50,'Digite o ID da assinatura aqui','headerSignature',2,'Digite o ID da assinatura aqui','StringSignature',315),
	 (NULL,NULL,'required','W9_PT',162,15,50,'Digite o ID da assinatura aqui','headerSignature1',3,'Digite o ID da assinatura aqui','StringSignature',315),
	 (NULL,NULL,'required','W9_PT',162,15,50,'Digite o ID da assinatura aqui','headerSignature2',4,'Digite o ID da assinatura aqui','StringSignature',315),
	 (NULL,NULL,'required','W9_PT',162,15,50,'Digite o ID da assinatura aqui','headerSignature3',5,'Digite o ID da assinatura aqui','StringSignature',315),
	 (NULL,NULL,'required','W9_PT',162,15,50,'Digite o ID da assinatura aqui','headerSignature4',6,'Digite o ID da assinatura aqui','StringSignature',315),
	 (NULL,NULL,' ','W9_PT',68,660,NULL,'Nome da empresa/nome da entidade desconsiderada, se diferente do acima','question2a',1,'Digite o nome da empresa','String',NULL),
	 (NULL,NULL,'','W9_PT',71,631,8,'Not to be Shown','question3',1,'Main Question 3','RadioMain',8);
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'','W9_PT',65,624,8,'Pessoa física/Proprietário individual','question3a',1,'Pessoa física/Proprietário individual','RadioOption',8),
	 (NULL,NULL,'','W9_PT',180,626,8,'Corporação C','question3b',1,'Corporação C','RadioOption',8),
	 (NULL,NULL,'','W9_PT',252,626,8,'Corporação S','question3c',1,'Corporação S','RadioOption',8),
	 (NULL,NULL,'','W9_PT',324,326,8,'Sociedade anônima','question3d',1,'Sociedade anônima','RadioOption',8),
	 (NULL,NULL,'','W9_PT',65,599,8,'Sociedade de responsabilidade limitada','question3f',1,'Sociedade de responsabilidade limitada','RadioOption',8),
	 (NULL,NULL,'','W9_PT',412,600,NULL,'(C= Corporação C, S=Corporação S, P=Sociedade anônima)','question3g',1,'Digite a classificação fiscal','String',NULL),
	 (NULL,NULL,'','W9_PT',65,553,8,'Outro','question3h',1,'Outro','RadioOption',8),
	 (NULL,NULL,'','W9_PT',162,555,NULL,'(consulte as instruções)','question3i',1,'Outros detalhes','String',NULL),
	 (NULL,NULL,'','W9_PT',543,614,NULL,'Código de beneficiário isento (se houver)','question4a',1,'Código (se houver)','String',NULL),
	 (NULL,NULL,'','W9_PT',506,575,NULL,'Isenção do código de relatório FATCA (se houver)','question4b',1,'Código (se houver)','String',NULL);
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'required','W9_PT',68,529,NULL,'Endereço (número, rua e número do apartamento ou suíte)','question5a',1,'Endereço (número, rua e número do apartamento ou suíte)','String',NULL),
	 (NULL,NULL,'required','W9_PT',69,505,NULL,'Cidade, estado e código postal','question5b',1,'Cidade, estado e código postal','String',NULL),
	 (NULL,NULL,'','W9_PT',393,531,NULL,'Nome e endereço do solicitante (opcional)','question6a',1,'Nome e endereço do solicitante (opcional)','String',NULL),
	 (NULL,NULL,'','W9_PT',393,506,NULL,'Endereço do solicitante (opcional)','question6b',1,'Endereço do solicitante (opcional)','String',NULL),
	 (NULL,NULL,'','W9_PT',69,481,NULL,'Relacione o(s) número(s) de conta(s) aqui (opcional)','question7a',1,'Relacione o(s) número(s) de conta(s) aqui (opcional)','String',NULL),
	 (NULL,NULL,'required','W9_PT',417,432,NULL,'SSN1','question8a',1,'SSN1','StringID',NULL),
	 (NULL,NULL,'required','W9_PT',476,432,NULL,'SSN2','question8b',1,'SSN2','StringID',NULL),
	 (NULL,NULL,'required','W9_PT',519,432,NULL,'SSN3','question8c',1,'SSN3','StringID',NULL),
	 (NULL,NULL,'required','W9_PT',417,386,NULL,'EID1','question9a',1,'EID1','StringID',NULL),
	 (NULL,NULL,'required','W9_PT',461,386,8,'EID2','question9b',1,'EID2','StringID',NULL);
INSERT INTO public.pdf_form_questions (created_at,updated_at,field_required,pdf_form,question_coordx,question_coordy,question_height,question_label,question_number,question_page_number,question_tool_tip,question_type,question_width) VALUES
	 (NULL,NULL,'required','W9_PT',68,684,NULL,'Nome (conforme consta em sua declaração de imposto de renda)','question1a',1,'Insira o nome','String',NULL),
	 (NULL,NULL,'','W9_PT',396,626,8,'Fideicomisso/propriedade','question3e',1,'Fideicomisso/propriedade','RadioOption',8),
	 (NULL,NULL,'required','USPCERT_PT',162,15,50,'Digite o ID da assinatura aqui','headerSignature1',3,'Digite o ID da assinatura aqui','StringSignature',315),
	 (NULL,NULL,'required','USPCERT_PT',NULL,NULL,8,'Certifico que tenho capacidade para assinar','certificationCheckbox1',2,'Certifico que tenho capacidade para assinar','CheckBox',8),
	 (NULL,NULL,'required','USPCERT_PT',162,15,50,'Digite o ID da assinatura aqui','headerSignature',1,'Digite o ID da assinatura aqui','StringSignature',315),
	 (NULL,NULL,'required','USPCERT_PT',217,681,NULL,'[Rubrique aqui se aplicável]','question1a',2,'Iniciais do tipo','String',NULL),
	 (NULL,NULL,'required','USPCERT_PT',217,606,NULL,'[Rubrique aqui se aplicável]','question2a',2,'Iniciais do tipo','String',NULL),
	 (NULL,NULL,'required','USPCERT_PT',73,251,50,'Digite o ID da assinatura aqui','certificationSignature',2,'Digite o ID da assinatura aqui','StringSignature',315),
	 (NULL,NULL,'required','USPCERT_PT',104,311,NULL,'Data (MM-DD-YYYY)','certificationSignaturedate',2,'Data (MM-DD-YYYY)','StringSignatureDate',NULL),
	 (NULL,NULL,'required','USPCERT_PT',162,15,50,'Digite o ID da assinatura aqui','headerSignature2',4,'Digite o ID da assinatura aqui','StringSignature',315);
